db = connect("mongodb://localhost/optica_CMC");
db.empleats.insertMany([
  {
    empleat_id: 1,
    nom: "Maria Lens",
  },
  {
    empleat_id: 2,
    nom: "Toni Garcia",
  },
]);
db.addresses.insertMany([
  {
    calle: "Highland St",
    number: 121,
    piso: 3,
    puerta: 6,
    cuidad: "London",
    codigoPostal: "SW1234",
    pais: "England",
  },
  {
    calle: "Santa Gloria",
    number: 14,
    piso: 4,
    puerta: 4,
    cuidad: "Roma",
    codigoPostal: "RM7676",
    pais: "Italia",
  },
]);
db.proveidors.insertMany([
  {
    nom: "ProviderOne",
    adreca: {
      calle: "Highland St",
      number: 121,
      piso: 3,
      puerta: 6,
      cuidad: "London",
      codigoPostal: "SW1234",
      pais: "England",
    },
    telefon: "123456789",
    fax: "445588965",
    NIF: "FE123456",
  },
  {
    nom: "ProviderTwo",
    adreca: {
      calle: "Santa Gloria",
      number: 14,
      piso: 4,
      puerta: 4,
      cuidad: "Roma",
      codigoPostal: "RM7676",
      pais: "Italia",
    },
    telefon: "552778899",
    fax: "111222333",
    NIF: "TY883456",
  },
]);
db.clients.insertMany([
  {
    nom: "Carla Mendez",
    adreca: {
      calle: "San Felipe Norte",
      number: 53,
      piso: 2,
      cuidad: "Girona",
      codigoPostal: "RM4545",
      pais: "España",
    },
    correoElectronic: "carla@mail.com",
    telefon: "123456789",
    dataRegistre: "2022-10-10",
    recommanat: "Si",
  },
  {
    nom: "Rita Sanchez",
    adreca: {
      calle: "Santapi",
      number: 186,
      piso: 6,
      puerta: 1,
      cuidad: "Girona",
      codigoPostal: "RM4545",
      pais: "España",
    },
    telefon: "619885522",
    correuElectrònic: "rita27@mail.com",
    dataRegistre: "2022-10-10",
    recommanat: "No",
  },
  {
    nom: "Pep Garolli",
    adreca: {
      calle: "Santa Gloria",
      number: 14,
      piso: 4,
      puerta: 4,
      cuidad: "Lleida",
      codigoPostal: "08021",
      pais: "España",
    },
    telefon: "670115599",
    correuElectrònic: "PG@mail.com",
    dataRegistre: "2021-12-12",
    recommanat: "No",
  },
  {
    nom: "Ulises Marques",
    adreca: {
      calle: "Prades 11",
      number: 145,
      cuidad: "Lleida",
      codigoPostal: "MK9875",
      pais: "España",
    },
    telefon: "681448811",
    correuElectrònic: "uli1983@mail.com",
    dataRegistre: "2022-01-01",
    recommanat: "Si",
  },
]);
db.optica.insertMany([
  {
    empleats: [
      {
        empleat_id: 1,
        nom: "Maria Lens",
      },
      {
        empleat_id: 2,
        nom: "Toni Garcia",
      },
    ],
    proveidors: [
      {
        nom: "ProviderOne",
        adreca: {
          calle: "Highland St",
          number: 121,
          piso: 3,
          puerta: 6,
          cuidad: "London",
          codigoPostal: "SW1234",
          pais: "England",
        },
        telefon: "123456789",
        fax: "445588965",
        NIF: "FE123456",
      },
      {
        nom: "ProviderTwo",
        adreca: {
          calle: "Santa Gloria",
          number: 14,
          piso: 4,
          puerta: 4,
          cuidad: "Roma",
          codigoPostal: "RM7676",
          pais: "Italia",
        },
        telefon: "552778899",
        fax: "111222333",
        NIF: "TY883456",
      },
    ],
    clients: [
      {
        nom: "Carla Mendez",
        adreca: {
          calle: "San Felipe Norte",
          number: 53,
          piso: 2,
          cuidad: "Girona",
          codigoPostal: "RM4545",
          pais: "España",
        },
        correoElectronic: "carla@mail.com",
        telefon: "123456789",
        dataRegistre: "2022-10-10",
        recommanat: "Si",
      },
      {
        nom: "Rita Sanchez",
        adreca: {
          calle: "Santapi",
          number: 186,
          piso: 6,
          puerta: 1,
          cuidad: "Girona",
          codigoPostal: "RM4545",
          pais: "España",
        },
        telefon: "619885522",
        correuElectrònic: "rita27@mail.com",
        dataRegistre: "2022-10-10",
        recommanat: "No",
      },
      {
        nom: "Pep Garolli",
        adreca: {
          calle: "Santa Gloria",
          number: 14,
          piso: 4,
          puerta: 4,
          cuidad: "Lleida",
          codigoPostal: "08021",
          pais: "España",
        },
        telefon: "670115599",
        correuElectrònic: "PG@mail.com",
        dataRegistre: "2021-12-12",
        recommanat: "No",
      },
      {
        nom: "Ulises Marques",
        adreca: {
          calle: "Prades 11",
          number: 145,
          cuidad: "Lleida",
          codigoPostal: "MK9875",
          pais: "España",
        },
        telefon: "681448811",
        correuElectrònic: "uli1983@mail.com",
        dataRegistre: "2022-01-01",
        recommanat: "Si",
      },
    ],
  },
]);
db.ulleres.insertMany([
  {
    marca: "chanel",
    graduacion: "+0.5",
    muntura: "metal",
    colorMuntura: "grey",
    colorVidres: "blue",
    preu: 91.0,
    proveidorID: "1",
    opticaID: 1,
  },
  {
    marca: "chanel",
    graduacion: "+0.5",
    muntura: "plastic",
    colorMuntura: "white",
    colorVidres: "clear",
    preu: 15.0,
    proveidor: "1",
    opticaID: 1,
  },
  {
    marca: "ray",
    graduacion: "+0.5",
    muntura: "metal",
    colorMuntura: "grey",
    colorVidres: "blue",
    preu: 45.0,
    proveidor: "2",
    opticaID: 1,
  },
  {
    marca: "blue-jean",
    graduacion: "+0.5",
    muntura: "plastic",
    colorMuntura: "pink",
    colorVidres: "blue",
    preu: 62.0,
    proveidor: "2",
    opticaID: 1,
  },
  {
    marca: "chanel",
    graduacion: "+2.5",
    muntura: "plastic",
    colorMuntura: "red",
    colorVidres: "clear",
    preu: 85.0,
    proveidor: "1",
    opticaID: 1,
  },
  {
    marca: "blue-jean",
    graduacion: "-1.5",
    muntura: "plastic",
    colorMuntura: "grey",
    colorVidres: "clear",
    preu: 60.0,
    proveidor: "2",
    opticaID: 1,
  },
  {
    marca: "blue-jean",
    graduacion: "+1.5",
    muntura: "metal",
    colorMuntura: "blue",
    colorVidres: "clear",
    preu: 40.0,
    proveidor: "2",
    opticaID: 1,
  },
  {
    marca: "ray",
    graduacion: "+1.5",
    muntura: "plastic",
    colorMuntura: "black",
    colorVidres: "clear",
    preu: 75.0,
    proveidor: "2",
    opticaID: 1,
  },
  {
    marca: "ray",
    graduacion: "-0.5",
    muntura: "plastic",
    colorMuntura: "grey",
    colorVidres: "clear",
    preu: 80.0,
    proveidor: "2",
    opticaID: 1,
  },
  {
    marca: "chanel",
    graduacion: "-0.5",
    muntura: "metal",
    colorMuntura: "black",
    colorVidres: "clear",
    preu: 99.0,
    proveidor: "1",
    opticaID: 1,
  },
]);
db.vendes.insertMany([
  {
    empleat: "Maria Lens",
    fecha: "2020-07-07",
    client_id: "1",
    ulleres_id: "1",
    botiga_id: 1,
  },
  {
    empleat: "Maria Lens",
    fecha: "2021-04-04",
    client_id: "6",
    ulleres_id: "3",
    botiga_id: 1,
  },
  {
    empleat: "Maria Lens",
    fecha: "2021-11-11",
    client_id: "3",
    ulleres_id: "6",
    botiga_id: 1,
  },
  {
    empleat: "Toni Garcia",
    fecha: "2021-12-12",
    client_id: "5",
    ulleres_id: "8",
    botiga_id: 1,
  },
  {
    empleat: "Toni Garcia",
    fecha: "2021-12-12",
    client_id: "5",
    ulleres_id: "6",
    botiga_id: 1,
  },
  {
    empleat: "Maria Lens",
    fecha: "2022-03-03",
    client_id: "2",
    ulleres_id: "4",
    botiga_id: 1,
  },
  {
    empleat: "Toni Garcia",
    fecha: "2022-02-02",
    client_id: "4",
    ulleres_id: "10",
    botiga_id: 1,
  },
  {
    empleat: "Maria Lens",
    fecha: "2022-02-02",
    client_id: "1",
    ulleres_id: "2",
    botiga_id: 1,
  },
]);
