db.restaurants.find();
db.restaurants.find({}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1});
db.restaurants.find({}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0});
db.restaurants.find({}, {"restaurant_id": 1, "name": 1, "borough": 1, "address.zipcode": 1, "_id": 0});
db.restaurants.find({"borough": "Bronx"});
db.restaurants.find({"borough": "Bronx"}).limit(5);
db.restaurants.find({"borough": "Bronx"}).skip(5).limit(5);
db.restaurants.find({"grades": {"$elemMatch": {"score": {"$gte": 90}}}});
db.restaurants.find({"grades": {"$elemMatch": {"score": {"$gte": 80, "$lte": 100}}}});
db.restaurants.find({"address.coord.0": {"$lt": -95.754168}});
db.restaurants.find({"address.coord.0": {"$lt": -65.754168}, "cuisine": { "$ne": "American "}, "grades.score": {"$gt": 70}});
db.restaurants.find({"address.coord.1": {"$lt": 65.754168}, "cuisine": { "$ne": "American "}, "grades.score": {"$gt": 70}});
db.restaurants.find({"borough": {"$ne": "Brooklyn"}, "cuisine": {"$ne": "American "}, "grades.grade": "A"}).sort({"cuisine": -1});
db.restaurants.find({"name": { $regex: '^Wil'}}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0} );
db.restaurants.find({"name": { $regex: 'ces$'}} );
db.restaurants.find({"name": { $regex: 'Reg'}}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0} );
db.restaurants.find({"$and": [{ "borough": "Brooklyn"}, { "$or": [ { "cuisine": "American " }, { "cuisine": "Chinese"}]}]} );
db.restaurants.find({"$or": [{"borough": "Staten Island"}, {"borough": "Queens"}, {"borough": "Brooklyn"}, {"borough": "Bronx"}]}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0} );
db.restaurants.find({"$nor": [{"borough": "Staten Island"}, {"borough": "Queens"}, {"borough": "Brooklyn"}, {"borough": "Bronx"}]}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0} );
db.restaurants.find({"grades": {"$elemMatch": {"score": {"$lt": 10}}}}, {"restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1, "_id": 0});
db.restaurants.find({"$and": [{"grades.grade": "A"}, {"$and": [{"grades.score": 11}, {"grades.date": ISODate("2014-08-11T00:00:00Z")}]}]});
db.restaurants.find({"$and": [{"grades.1.grade": "A"}, {"grades.1.score": 9}, {"grades.score": 11}, {"grades.1.date": ISODate("2014-08-11T00:00:00Z")}]}, {"restaurant_id": 1, "name": 1, "grades": 1, "_id": 0});
db.restaurants.find( {"address.coord.1": {"$gte": 42, "$lte": 52}}, {"restaurant_id": 1, "name": 1, "address": 1, "_id": 0} );
db.restaurants.find().sort({"name": 1});
db.restaurants.find().sort({"name": -1});
db.restaurants.find().sort({"cuisine": 1, "borough": -1});
db.restaurants.find({"address.street": { $regex: 'Street'}} );
db.restaurants.find({"address.coord": { $type : "double" } });
db.restaurants.find( { "grades": {"$elemMatch": {"score": { $mod: [ 7, 0 ]}}}}, {"restaurant_id": 1, "name": 1, "grades.grade": 1, "_id": 0});
db.restaurants.find({"name": { $regex: 'mon'}}, {"restaurant_id": 1, "name": 1, "address.coord": 1, "cuisine": 1, "_id": 0});
db.restaurants.find({"name": { $regex: '^Mad'}}, {"restaurant_id": 1, "name": 1, "address.coord": 1, "cuisine": 1, "_id": 0});