db = connect("mongodb://localhost/youtube_CMC");
db.labels.insertMany([
  {
    label_id: 1,
    label: "comedy",
  },
  {
    empleat_id: 2,
    label: "modern",
  },
  {
    label_id: 3,
    label: "classic",
  },
  {
    empleat_id: 4,
    label: "news",
  },
]);
db.likesDislikes.insertMany([
  {
    _id: 1,
    usuari_ID: 3,
    dataFet: new Timestamp(),
    response: "Like",
  },
  {
    _id: 2,
    usuari_ID: 3,
    dataFet: new Timestamp(),
    response: "Dislike",
  },
  {
    _id: 3,
    usuari_ID: 4,
    dataFet: new Timestamp(),
    response: "Like",
  },
  {
    _id: 4,
    usuari_ID: 4,
    dataFet: new Timestamp(),
    response: "Like",
  },
  {
    _id: 5,
    usuari_ID: 5,
    dataFet: new Timestamp(),
    response: "Like",
  },
  {
    _id: 6,
    usuari_ID: 4,
    dataFet: new Timestamp(),
    response: "Like",
  },
  {
    _id: 7,
    usuari_ID: 3,
    dataFet: new Timestamp(),
    response: "Like",
  },
  {
    _id: 8,
    usuari_ID: 2,
    dataFet: new Timestamp(),
    response: "Like",
  },
  {
    _id: 9,
    usuari_ID: 3,
    dataFet: new Timestamp(),
    response: "Like",
  },
]);

db.videos.insertMany([
  {
    titol: "Falling",
    description: "very funny film clip",
    grandària: "2",
    nomarxiu: "comedy",
    durada: 120,
    thumbnail: null,
    estat: "public",
    UsuariId: 1,
    dataPublica: new Timestamp(),
    reproCount: 1269,
    label: {
      label_id: 1,
      label: "comedy",
    },
    responses: [
      {
        _id: 6,
        usuari_ID: 4,
        dataFet: new Timestamp(),
        response: "Like",
      },
    ],
  },
  {
    titol: "Red Tiles",
    description: "very modern film clip",
    grandària: "1",
    nomarxiu: "modern",
    durada: 60,
    estat: "public",
    UsuariId: 2,
    dataPublica: new Timestamp(),
    reproCount: 103,
    label: {
      label_id: 2,
      label: "modern",
    },
    responses: [
      {
        _id: 7,
        usuari_ID: 3,
        dataFet: new Timestamp(),
        response: "Like",
      },
      {
        _id: 8,
        usuari_ID: 2,
        dataFet: new Timestamp(),
        response: "Like",
      },
      {
        _id: 9,
        usuari_ID: 4,
        dataFet: new Timestamp(),
        response: "Dislike",
      },
    ],
  },
  {
    titol: "Blue Skies",
    description: "very classic film clip",
    grandària: "1",
    nomarxiu: "classic",
    durada: 60,
    thumbnail: null,
    estat: "public",
    UsuariId: 2,
    dataPublica: new Timestamp(),
    reproCount: 223,
    label: {
      label_id: 3,
      label: "classic",
    },
    responses: [
      {
        _id: 4,
        usuari_ID: 4,
        dataFet: new Timestamp(),
        response: "Dislike",
      },
      {
        _id: 5,
        usuari_ID: 5,
        dataFet: new Timestamp(),
        response: "Like",
      },
    ],
  },
  {
    titol: "Diff",
    description: "very different film clip",
    grandària: "2",
    nomarxiu: "different",
    durada: 100,
    thumbnail: null,
    estat: "public",
    UsuariId: 1,
    dataPublica: new Timestamp(),
    reproCount: 4,
  },
  {
    titol: "Truthy",
    description: "very Truthy news film clip",
    grandària: "1",
    nomarxiu: "news",
    durada: 30,
    thumbnail: null,
    estat: "privat",
    UsuariId: 1,
    dataPublica: new Timestamp(),
    reproCount: 2,
    label: {
      label_id: 4,
      label: "news",
    },
    responses: [
      {
        _id: 3,
        usuari_ID: 4,
        dataFet: new Timestamp(),
        response: "Like",
      },
    ],
  },
  {
    titol: "Halo signs",
    description: "very film clip",
    grandària: "1",
    nomarxiu: "modern",
    durada: 60,
    estat: "privat",
    UsuariId: 3,
    dataPublica: new Timestamp(),
    label: {
      label_id: 2,
      label: "modern",
    },
  },
  {
    titol: "Red",
    description: "very clip clip",
    grandària: "1",
    nomarxiu: "classic",
    durada: 60,
    thumbnail: null,
    estat: "privat",
    UsuariId: 2,
    dataPublica: new Timestamp(),
    label: {
      label_id: 3,
      label: "classic",
    },
  },
  {
    titol: "Other",
    description: "very another time",
    grandària: "2",
    nomarxiu: "comedy",
    durada: 60,
    thumbnail: null,
    estat: "public",
    UsuariId: 3,
    dataPublica: new Timestamp(),
    reproCount: 3,
    label: {
      label_id: 1,
      label: "comedy",
    },
  },
  {
    titol: "Falsy",
    description: "very falsy time",
    grandària: "1",
    nomarxiu: "news",
    durada: 30,
    thumbnail: null,
    estat: "public",
    UsuariId: 2,
    dataPublica: new Timestamp(),
    reproCount: 2,
    label: {
      label_id: 4,
      label: "news",
    },
  },
]);
db.usuari.insertMany([
  {
    id: 1,
    email: "yeti@youtube.com",
    password: "Password1",
    nomUsuari: "yeti-101",
    dataNax: "1989-12-12",
    sexe: "F",
    pais: "España",
    CP: "05826",
    canal: {
      canal_id: "1",
      nom: "my life on youtube",
      description: "everything I do, I do it on youtube ",
      dataCreatio: new Timestamp(),
      subscribers: [{ userID: "4" }],
    },
    playlists: [
      {
        playlistID: 1,
        nom: "makes me laugh",
        dataCreacio: new Timestamp(),
        vidoeIDs: [1, 5, 6],
        estat: "publica",
      },
      {
        playlistID: 2,
        nom: "Good news",
        dataCreacio: new Timestamp(),
        vidoeIDs: [3, 8],
        estat: "publica",
      },
    ],
  },
  {
    id: 2,
    email: "maya@gmail.com",
    password: "Password2",
    nomUsuari: "maya1985",
    dataNax: "1979-11-11",
    sexe: "O",
    pais: "España",
    CP: "08092",
    playlists: [
      {
        playlistID: 3,
        nom: "Research",
        dataCreacio: new Timestamp(),
        vidoeIDs: [4, 7],
        estat: "publica",
      },
    ],
  },
  {
    id: 3,
    email: "frank@hotmail.com",
    password: "Password3",
    nomUsuari: "franky",
    dataNax: "1999-06-06",
    sexe: "M",
    pais: "España",
    CP: "12504",
  },
  {
    id: 4,
    email: "rosa21@mailDrake.com",
    password: "Password4",
    nomUsuari: "rosa_gs",
    dataNax: "2004-03-03",
    sexe: "F",
    pais: "España",
    CP: "08062",
  },
]);
db.commentaris.insertMany([
  {
    commentariText: "I like this. ",
    dataRealitzat: new Timestamp(),
    nomUsuari: "rosa_gs",
    responses: [
      {
        _id: 1,
        usuari_ID: 3,
        dataFet: new Timestamp(),
        response: "Like",
      },
      {
        _id: 2,
        usuari_ID: 3,
        dataFet: new Timestamp(),
        response: "Dislike",
      },
    ],
    videoId: 1,
  },
  {
    commentariText: "Very good. ",
    dataRealitzat: new Timestamp(),
    nomUsuari: "maya1985",
    videoId: 6,
  },
]);
