db = connect("mongodb://localhost/cmoptica");
db.proveidor.insertMany([
  {
    _id: 1,
    nom: "ProviderOne",
    adreca: ["Highland St", "121", "3", "6", "London", "SW1234", "England"],
    telefon: "123456789",
    fax: "445588965",
    NIF: "FE123456",
    ulleres: [
      {
        _id: 1,
        marca: "chanel",
        graduacion: "+0.5",
        muntura: "metal",
        colorMuntura: "grey",
        colorVidres: "blue",
        preu: "9100",
        proveidor: "1",
      },
      {
        _id: 2,
        marca: "chanel",
        graduacion: "+0.5",
        muntura: "plastic",
        colorMuntura: "white",
        colorVidres: "clear",
        preu: "1500",
        proveidor: "1",
      },
      {
        _id: 3,
        marca: "chanel",
        graduacion: "+2.5",
        muntura: "plastic",
        colorMuntura: "red",
        colorVidres: "clear",
        preu: "8500",
        proveidor: "1",
      },
      {
        _id: 4,
        marca: "chanel",
        graduacion: "-0.5",
        muntura: "metal",
        colorMuntura: "black",
        colorVidres: "clear",
        preu: "9900",
        proveidor: "1",
      },
    ],
  },
  {
    _id: 2,
    nom: "ProviderTwo",
    adreca: ["Santa Gloria", "14", "4", "4C", "Roma", "RM7676", "Italia"],
    telefon: "552778899",
    fax: "111222333",
    NIF: "FE123456",
    ulleres: [
      {
        _id: 5,
        marca: "ray",
        graduacion: "+0.5",
        muntura: "metal",
        colorMuntura: "grey",
        colorVidres: "blue",
        preu: "4500",
        proveidor: "2",
      },
      {
        _id: 6,
        marca: "blue-jean",
        graduacion: "+0.5",
        muntura: "plastic",
        colorMuntura: "pink",
        colorVidres: "blue",
        preu: "6200",
        proveidor: "2",
      },
      {
        _id: 7,
        marca: "blue-jean",
        graduacion: "-1.5",
        muntura: "plastic",
        colorMuntura: "grey",
        colorVidres: "clear",
        preu: "6000",
        proveidor: "2",
      },
      {
        _id: 8,
        marca: "blue-jean",
        graduacion: "+1.5",
        muntura: "metal",
        colorMuntura: "blue",
        colorVidres: "clear",
        preu: "4000",
        proveidor: "2",
      },
      {
        _id: 9,
        marca: "ray",
        graduacion: "+1.5",
        muntura: "plastic",
        colorMuntura: "black",
        colorVidres: "clear",
        preu: "7500",
        proveidor: "2",
      },
      {
        _id: 10,
        marca: "ray",
        graduacion: "-0.5",
        muntura: "plastic",
        colorMuntura: "grey",
        colorVidres: "clear",
        preu: "8000",
        proveidor: "2",
      },
    ],
  },
]);

db.client.insertMany([
  {
    _id: 1,
    nom: "Carla Mendez",
    adrecaPostal: "08014",
    telefon: "123456789",
    correuElectrònic: "carla@mail.com",
    dataDeRregistre: "2020-12-12",
    recommanat: "YES",
    vendes: [
      {
        _id: 1,
        fecha: "2020-07-07",
        ulleres_id: [1],
        empleat: { _id: 1, nom: "Maria Lens" },
      },
      {
        _id: 7,
        fecha: "2022-02-02",
        ulleres_id: [2],
        empleat: { _id: 1, nom: "Maria Lens" },
      },
    ],
  },
  {
    _id: 2,
    nom: "Rita Sanchez",
    adrecaPostal: "08016",
    telefon: "619885522",
    correuElectrònic: "rita27@mail.com",
    dataDeRregistre: "2022-10-10",
    recommanat: "NO",
    vendes: [
      {
        _id: 5,
        fecha: "2022-03-03",
        ulleres_id: [8],
        empleat: { _id: 1, nom: "Maria Lens" },
      },
    ],
  },
  {
    _id: 3,
    nom: "Pep Garolli",
    adrecaPostal: "08021",
    telefon: "670115599",
    correuElectrònic: "PG@mail.com",
    dataDeRregistre: "2021-12-12",
    recommanat: "YES",
    vendes: [
      {
        _id: 4,
        fecha: "2021-04-04",
        ulleres_id: [4],
        empleat: { _id: 1, nom: "Maria Lens" },
      },
    ],
  },
  {
    _id: 4,
    nom: "Ulises Marques",
    adrecaPostal: "08014",
    telefon: "681448811",
    correuElectrònic: "uli1983@mail.com",
    dataDeRregistre: "2022-01-01",
    recommanat: "YES",
    vendes: [
      {
        _id: 6,
        fecha: "2022-02-02",
        client_id: "4",
        ulleres_id: [10],
        empleat: { _id: 2, nom: "Toni Garcia" },
      },
    ],
  },
  {
    _id: 5,
    nom: "Julia Greiss",
    adrecaPostal: "08016",
    telefon: "617885533",
    correuElectrònic: "greiss11@mail.com",
    dataDeRregistre: "2021-01-01",
    recommanat: "NO",
    vendes: [
      {
        _id: 3,
        fecha: "2021-12-12",
        ulleres_id: [8],
        empleat: { _id: 2, nom: "Toni Garcia" },
      },
    ],
  },
  {
    _id: 6,
    nom: "Ulises B. Marques",
    adrecaPostal: "08014",
    telefon: "619998877",
    correuElectrònic: "uliB@mail.com",
    dataDeRregistre: "2022-03-03",
    recommanat: "YES",
    vendes: [
      {
        _id: 2,
        fecha: "2021-04-04",
        ulleres_id: [3],
        empleat: { _id: 1, nom: "Maria Lens" },
      },
    ],
  },
]);
